[project]
name = "insider-stock-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "pandas>=2.2.3",
    "pydantic>=2.11.5",
    "pydantic-ai>=0.2.12",
    "yfinance>=0.2.61",
]
